#!/usr/bin/env bun
// Synthesizes schema-valid stores; never accepts an existing database as input.
import { execFileSync, spawn } from "node:child_process";
import { appendFileSync, mkdirSync, mkdtempSync, realpathSync, statSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const taskRoot = join(realpathSync(tmpdir()), "magic-context", "issue-641");
mkdirSync(taskRoot, { recursive: true });
const root = mkdtempSync(join(taskRoot, "fixture-"));
const work = join(root, "work");
mkdirSync(work);
Object.assign(process.env, { HOME: root, CFFIXED_USER_HOME: root, XDG_DATA_HOME: root, XDG_CONFIG_HOME: join(root,"config"),
  XDG_STATE_HOME: join(root,"state"), XDG_RUNTIME_DIR: join(root,"runtime"), MAGIC_CONTEXT_STORAGE_DIR: root,
  MAGIC_CONTEXT_TEST_DATA_DIR: root, OPENCODE_DB: join(root,"opencode.db"), MAGIC_CONTEXT_LOG_PATH: join(root,"mc.log"), NODE_ENV: "test" });
execFileSync("git", ["init", "-q", work]);
execFileSync("git", ["-C", work, "remote", "add", "origin", "https://example.invalid/issue-641-fixture.git"]);
const { Database } = await import("../../../../packages/plugin/src/shared/sqlite");
const { initializeDatabase } = await import("../../../../packages/plugin/src/features/magic-context/storage-db");
const { runMigrations } = await import("../../../../packages/plugin/src/features/magic-context/migrations");
const { appendCompartments } = await import("../../../../packages/plugin/src/features/magic-context/compartment-storage");
const { setPendingPiCompactionMarkerState, updateSessionMeta } = await import("../../../../packages/plugin/src/features/magic-context/storage");
const { signalPiDeferredHistoryRefresh, signalPiDeferredMaterialization } = await import("../../../../packages/pi-plugin/src/context-handler");
const { setHarness } = await import("../../../../packages/plugin/src/shared/harness");
const { generateSyntheticFixture } = await import("../../../../packages/pi-plugin/scripts/experiments/perf/fixtures");
const { createDatabaseTimer, createTimingCollector } = await import("../../../../packages/pi-plugin/scripts/experiments/perf/instrumentation");
const { registerPiContextHandler, clearContextHandlerSession, __test } = await import("../../../../packages/pi-plugin/src/context-handler");
const { setPiTransformTimingObserver } = await import("../../../../packages/pi-plugin/src/context-perf-hooks");
const { tokenizePiMessages } = await import("../../../../packages/pi-plugin/src/tokenize-pi-messages");
setHarness("pi");
const fixture = generateSyntheticFixture({ messages: 600 });
for (const entry of fixture.entries) {
  const message = (entry as any).message;
  const text = `Synthetic entry ${entry.id}:` + " alpha".repeat(950);
  if (typeof message.content === "string") message.content = text;
  else {
    message.content = message.content.filter((part: any) => part.type !== "image");
    const part = message.content.find((part: any) => part.type === "text");
    if (part) part.text = text;
  }
}
const messages = fixture.entries.map((entry: any) => entry.message);
for (const message of messages) if (message.role === "assistant") { message.provider="cursor"; message.model="grok-4.7"; }
(messages.at(-1) as any).usage = { input:573414,output:100,cacheRead:0,cacheWrite:0,totalTokens:573514,cost:{input:0,output:0,cacheRead:0,cacheWrite:0,total:0} };
// Price the actual generated bytes, then pad the tail to the issue's pressure sample.
let tokens = tokenizePiMessages(messages);
const gap = 573414 - tokens.conversation - tokens.toolCall;
if (gap > 0) (messages.at(-1) as any).content.find((p: any) => p.type === "text").text += " alpha".repeat(gap);
tokens = tokenizePiMessages(messages);
writeFileSync(join(root,"session.jsonl"), [{type:"session",version:3,id:fixture.sessionId,timestamp:new Date().toISOString(),cwd:work}, ...fixture.entries].map(e => JSON.stringify(e)).join("\n")+"\n");
const reports: unknown[] = [];
for (const large of [false, true]) {
  const dbPath = join(root, large ? "large.db" : "small.db");
  const db = new Database(dbPath);
  initializeDatabase(db); runMigrations(db);
  db.exec("PRAGMA journal_mode=WAL");
  if (large) {
    const vector = new Float32Array(1536).fill(0.125);
    const chunkVector = new Float32Array(3072).fill(0.25);
    const memory = db.prepare(`INSERT INTO memories(id,project_path,category,content,normalized_hash,first_seen_at,created_at,updated_at,last_seen_at) VALUES(?,'https://example.invalid/issue-641-fixture','CONSTRAINTS',?,?,1,1,1,1)`);
    const embed = db.prepare("INSERT INTO memory_embeddings(memory_id,embedding,model_id) VALUES(?,?,'fixture:1536')");
    const comp = db.prepare("INSERT INTO compartments(id,session_id,sequence,start_message,end_message,title,content,created_at) VALUES(?,'archive',?,1,2,'Synthetic archive',?,1)");
    const chunk = db.prepare("INSERT INTO compartment_chunk_embeddings(compartment_id,session_id,project_path,harness,window_index,start_ordinal,end_ordinal,chunk_hash,model_id,dims,vector,created_at) VALUES(?,'archive','https://example.invalid/issue-641-fixture','pi',0,1,2,?,'fixture:3072',3072,?,1)");
    const fts = db.prepare("INSERT INTO message_history_fts(session_id,message_ordinal,message_id,role,content) VALUES('archive',?,?,'user',?)");
    const content = "Synthetic searchable archive alpha beta gamma delta evidence. ".repeat(30);
    db.transaction(() => {
      for (let i=1; i<=12000; i++) { comp.run(i,i,content); chunk.run(i,`chunk-${i}`,Buffer.from(chunkVector.buffer)); }
      for (let i=1; i<=17000; i++) { memory.run(i,`${content} ${i}`,`hash-${i}`); embed.run(i,Buffer.from(vector.buffer)); }
      for (let i=1; i<=5000; i++) fts.run(i,`archive-${i}`,content);
      db.exec("UPDATE message_fts_rowid_map_backfill_state SET completed=0,watermark_rowid=0; UPDATE message_time_backfill_state SET completed=0");
      db.exec("INSERT INTO tool_owner_backfill_state(session_id,status) VALUES('archive','pending')");
    })();
    db.exec("PRAGMA wal_checkpoint(TRUNCATE)");
    // Add memory/vector/FTS rows until the database reaches 394.2 MB, without an unrelated padding table.
    for (let i=17001; i<=40000 && statSync(dbPath).size < 394200000; i+=500) {
      db.transaction(() => { for(let j=i;j<i+500;j++) { memory.run(j,`${content} ${j}`,`hash-${j}`); embed.run(j,Buffer.from(vector.buffer)); } })();
      db.exec("PRAGMA wal_checkpoint(TRUNCATE)");
    }
  }
  db.exec("PRAGMA wal_checkpoint(TRUNCATE)");
  const shape = { bytes:statSync(dbPath).size, tables:db.prepare("SELECT count(*) AS n FROM sqlite_master WHERE type='table'").get(),
    counts:Object.fromEntries(["memories","memory_embeddings","compartments","compartment_chunk_embeddings","message_history_fts","tool_owner_backfill_state"].map(t => [t, db.prepare(`SELECT count(*) AS n FROM ${t}`).get()])),
    pragmas: { autocheckpoint: db.prepare("PRAGMA wal_autocheckpoint").get(), pageSize:db.prepare("PRAGMA page_size").get() } };
  const dbTimer = createDatabaseTimer(db);
  const timings = createTimingCollector();
  const restore = setPiTransformTimingObserver(sample => timings.observe(sample));
  const handlers = new Map<string, (...args: any[]) => any>();
  const markers: unknown[] = [];
  const settings = {
    db:dbTimer.database as never, protectedTags:20,
    scheduler:{executeThresholdPercentage:65}, heuristics:{caveman:{enabled:false,minChars:2000}},
    injection:{memoryEnabled:false,injectDocs:false,injectionBudgetTokens:4000,temporalAwareness:false},
    autoSearch:{enabled:false,minPromptChars:1,scoreThreshold:0.99},
  };
  registerPiContextHandler({ on:(name: string, fn: (...args:any[])=>any)=>handlers.set(name,fn) } as never, settings);
  const lsof = execFileSync("/usr/sbin/lsof",["-p",String(process.pid)],{encoding:"utf8"});
  writeFileSync(join(root,large?"large-lsof.txt":"small-lsof.txt"),lsof);
  const dbLines = lsof.split("\n").filter(line=>/\.db(?:[- ]|$)/.test(line));
  if (!dbLines.length || dbLines.some(line=>!line.includes(root))) throw new Error("fixture isolation failed");
  if (large && (shape.bytes < 390000000 || shape.bytes > 410000000)) throw new Error("large fixture size missed target");
  const sessionId = fixture.sessionId;
  const byId = new Map(fixture.entries.map(entry => [entry.id,entry]));
  const ctx = {cwd:work,hasUI:false,ui:{notify:()=>{}},
    model:{provider:"cursor",id:"grok-4.7",contextWindow:256000,maxTokens:32000},
    sessionManager:{getSessionId:()=>sessionId,getLeafId:()=>fixture.entries.at(-1)?.id,getBranch:()=>fixture.entries,getEntry:(id:string)=>byId.get(id),
      appendCompaction:(summary:string,firstKeptEntryId:string,tokensBefore:number,details:unknown,fromHook:boolean)=> {
        const marker={type:"compaction",id:`marker-${markers.length}`,parentId:fixture.entries.at(-1)?.id,timestamp:new Date().toISOString(),summary,firstKeptEntryId,tokensBefore,details,fromHook};
        markers.push({at:Date.now(),marker}); appendFileSync(join(root,large?"large-markers.jsonl":"small-markers.jsonl"),JSON.stringify(marker)+"\n"); return marker.id;
      }},
    getContextUsage:()=>({tokens:573414,percent:573414/256000*100,contextWindow:256000}) };
  for (const lane of large ? ["cold", "warm", "auto-search", "historian-wait"] : ["cold","warm"]) {
    settings.autoSearch.enabled = lane === "auto-search";
    if (lane === "auto-search") {
      const entry:any = {type:"message",id:"search-tail",parentId:fixture.entries.at(-1)?.id,timestamp:new Date().toISOString(),message:{role:"user",content:"Find synthetic searchable archive alpha beta gamma evidence from earlier work.",timestamp:Date.now()}};
      fixture.entries.push(entry); messages.push(entry.message); byId.set(entry.id,entry);
    }
    if (lane === "historian-wait") {
      db.exec("UPDATE tags SET status='active'");
      appendCompartments(db,sessionId,[{sequence:0,startMessage:1,endMessage:3,startMessageId:fixture.entries[0]!.id,endMessageId:fixture.entries[2]!.id,title:"Late boundary",content:"Synthetic folded prefix"}]);
      setPendingPiCompactionMarkerState(db,sessionId,{firstKeptEntryId:fixture.entries[3]!.id,endMessageId:fixture.entries[2]!.id,ordinal:3,tokensBefore:573414,summary:"Synthetic deadline marker",publishedAt:Date.now()});
      signalPiDeferredHistoryRefresh(sessionId); signalPiDeferredMaterialization(sessionId);
      updateSessionMeta(db,sessionId,{lastInputTokens:573414,lastContextPercentage:256,lastResponseTime:Date.now(),cacheTtl:"59m"});
    }
    timings.reset(); dbTimer.reset();
    const start = performance.now();
    const restoreHistorian = lane === "historian-wait" ? __test.setInFlightHistorianForTests(sessionId,new Promise(()=>{})) : ()=>{};
    let hostDeadline: unknown = null;
    const timer = setTimeout(()=> { hostDeadline = {elapsedMs:performance.now()-start,tags:db.prepare("SELECT status,count(*) AS n FROM tags GROUP BY status").all(),decisions:db.prepare("SELECT count(*) AS n FROM transform_decisions").get()}; },30000);
    try {
      const result = await handlers.get("context")!({messages:structuredClone(messages)},ctx);
      const wallMs = performance.now()-start;
      if (lane === "historian-wait" && (!hostDeadline || wallMs < 30000)) throw new Error("emergency historian wait did not overrun deadline");
      const foregroundDb = dbTimer.snapshot(); const queries = dbTimer.queries(); const stages = timings.samples();
      await Bun.sleep(250);
      const checkpointStart = performance.now();
      const checkpoint = db.prepare("PRAGMA wal_checkpoint(PASSIVE)").all();
      const checkpointMs = performance.now()-checkpointStart;
      reports.push({large,lane,shape,tokens,wallMs,hostDeadline,stages,db:foregroundDb,queries,
        outputMessages:result?.messages?.length,outputTokens:tokenizePiMessages(result?.messages ?? []),checkpoint,checkpointMs,markers:structuredClone(markers),
        tags:db.prepare("SELECT status,count(*) AS n FROM tags GROUP BY status").all(),
        decisions:db.prepare("SELECT * FROM transform_decisions").all(),
        meta:db.prepare("SELECT * FROM session_meta WHERE session_id=?").get(sessionId),
        lkg:db.prepare("SELECT * FROM lkg_slots").all()});
      console.log(JSON.stringify({large,lane,bytes:shape.bytes,tokens,wallMs,hostDeadline,stages,db:foregroundDb}));
    } finally {clearTimeout(timer);restoreHistorian();}
  }
  const locker = spawn("python3",["-u","-c","import sqlite3,sys,time;c=sqlite3.connect(sys.argv[1]);c.execute('BEGIN IMMEDIATE');print('LOCKED',flush=True);time.sleep(60)",dbPath],{stdio:["ignore","pipe","pipe"]});
  await new Promise<void>((done,fail)=>{locker.stdout!.once("data",()=>done());locker.once("error",fail);});
  const lockerLsof = execFileSync("/usr/sbin/lsof",["-p",String(locker.pid)],{encoding:"utf8"});
  writeFileSync(join(root,large?"large-locker-lsof.txt":"small-locker-lsof.txt"),lockerLsof);
  if (lockerLsof.split("\n").filter(line=>/\.db(?:[- ]|$)/.test(line)).some(line=>!line.includes(root))) throw new Error("locker isolation failed");
  timings.reset(); dbTimer.reset();
  const writerStart = performance.now();
  let writerOutcome = "returned";
  try { await handlers.get("context")!({messages:structuredClone(messages)},{...ctx,sessionManager:{...ctx.sessionManager,getSessionId:()=>`${sessionId}-locked-${large}`}}); }
  catch(error) { writerOutcome=String(error); }
  finally { locker.kill("SIGTERM"); await new Promise(done=>locker.once("exit",done)); }
  reports.push({large,lane:"writer-expire",shape,wallMs:performance.now()-writerStart,writerOutcome,stages:timings.samples(),db:dbTimer.snapshot()});
  restore(); clearContextHandlerSession(sessionId); db.close();
}
writeFileSync(join(root,"report.json"),JSON.stringify({bun:Bun.version,root,reports},null,2));
console.log(`Evidence: ${root}/report.json`);
